---
- name: provision server
  hosts: cloud
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - create_server

- name: install python2 so we can use ansible
  hosts: discourseservers
  user: ubuntu
  become: true
  become_user: root
  gather_facts: no
  roles:
    - python2

- name: prepare discourse server
  hosts: discourseservers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - prepare_server

- name: prepare discourse cloud volume
  hosts: discourseservers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - prepare_volume

- name: install discourse
  hosts: discourseservers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - autoupgrade
    - fail2ban
    - discourse
    - Datadog.datadog
    - datadog_docker
    - datadog_http
