---
- name: provision server
  hosts: cloud
  connection: local
  vars_files:
    - "vars/dreamcompute.yml"
  roles:
    - create_server

- name: prepare discourse
  hosts: discourseservers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/dreamcompute.yml"
  roles:
    - autoupgrade
    - fail2ban
    - discourse
