---
- name: create filesystem on volume
  filesystem:
    dev: "/dev/vdb"
    fstype: ext4

- name: create mountpoint for volume
  file:
    mode: 0700
    path: "/var/discourse"
    state: directory

- name: mount volume
  mount:
    fstype: ext4
    src: "/dev/vdb"
    state: mounted
    name: "/var/discourse"

- name: install docker
  apt:
    name: docker.io
    state: installed

- name: clone discourse docker repo
  git:
    repo: "https://github.com/discourse/discourse_docker.git"
    dest: "/var/discourse/discourse_docker"

- name: "check if discourse is already configured"
  stat:
    path: "/var/discourse/discourse_docker/containers/app.yml"
  register: app_config

- name: create setup script input file
  template:
    src: templates/setup_input.j2
    dest: /tmp/setup_input
    owner: root
    group: root
    mode: 0600
  when: app_config.stat.exists == False

- name: run discourse setup
  shell: "./discourse-setup < /tmp/setup_input"
  args:
    chdir: /var/discourse/discourse_docker
  when: app_config.stat.exists == False
