---
- name: create ext4 filesystem on discourse volume
  filesystem:
    dev: "/dev/vdb"
    fstype: ext4

- name: create mountpoint for discourse volume at /var/discourse
  file:
    mode: 0700
    path: "/var/discourse"
    state: directory

- name: mount the discourse volume at /var/discourse
  mount:
    fstype: ext4
    src: "/dev/vdb"
    state: mounted
    name: "/var/discourse"

