---
- name: prepare docker install
  apt: name="{{ item }}" state=installed update_cache=yes
  with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - unzip
     - python-dateutil

- name: install docker gpg key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

- name: add docker official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
  when: ansible_distribution_release == "xenial"

- name: prepare docker install
  apt: name="{{ item }}" state=installed update_cache=yes
  with_items:
     - docker-ce
  when: ansible_distribution_release == "xenial"

- name: add docker official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable"
    state: present
  when: ansible_distribution_release == "trusty"

- name: prepare docker install
  apt: name="{{ item }}" state=installed update_cache=yes
  with_items:
     - software-properties-common
     - linux-image-extra-virtual
     - docker-ce
  when: ansible_distribution_release == "trusty"

- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
            removes=/var/run/reboot-required

- name: wait for reboot
  wait_for: port=22 host="{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}" search_regex=OpenSSH delay=10
  sudo: no
  connection: local

- name: load AUFS module
  modprobe:
    name: aufs
    state: present

- name: force docker to use AUFS
  shell: 'echo "DOCKER_OPTS=\"-s aufs\"" >> /etc/default/docker'

