---
- name: Create volume for discourse data
  os_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    size: "{{ discourse.volume_size }}"
    wait: yes
    display_name: discourse-volume

- name: Create server
  os_server:
    state: "present"
    cloud: "{{ auth.cloud }}"
    name: discourse1
    image: "{{ discourse.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ discourse.flavor }}"
    network: public
    userdata: |
        {%- raw -%}#!/bin/bash
        systemctl stop sshd
        #systemctl disable sshd
        apt update && apt install -y python
        DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
        #systemctl enable sshd
        reboot
        {% endraw %}
    meta:
      hostname: discourse1
  register: discourse1

- name: attach a volume for database to save data
  os_server_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    server: discourse1
    volume: discourse-volume
    device: "/dev/vdb"

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.public_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 != ""

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.private_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 == ""

- name: wait for cloud-init to run
  pause: seconds=20

- name: wait for ssh
  wait_for:
    host: "{{ item }}"
    port: 22
    timeout: 900
    state: started
  with_items: "{{ groups.discourseservers }}"
