---
- name: Create volume for discourse data
  os_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    size: "{{ discourse.volume_size }}"
    wait: yes
    display_name: discourse-volume

- name: Create server
  os_server:
    state: "present"
    cloud: "{{ auth.cloud }}"
    name: discourse1
    image: "{{ discourse.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ discourse.flavor }}"
    network: public
    auto_ip: false
    meta:
      hostname: discourse1
  register: discourse1

- name: attach a volume for database to save data
  os_server_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    server: discourse1
    volume: discourse-volume
    device: "/dev/vdb"

- name: create discourse security group
  os_security_group:
    name: discourse
    state: present
    cloud: "{{ auth.cloud }}"

- name: Open port 80
  os_security_group_rule:
    security_group: discourse
    state: present
    cloud: "{{ auth.cloud }}"
    port_range_min: 80
    port_range_max: 80
    protocol: tcp

- name: Open port 443
  os_security_group_rule:
    security_group: discourse
    state: present
    cloud: "{{ auth.cloud }}"
    port_range_min: 443
    port_range_max: 443
    protocol: tcp

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.public_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 != ""

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.private_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 == ""

- name: wait for ssh
  wait_for:
    host: "{{ item }}"
    port: 22
    timeout: 60
    state: started
  with_items: "{{ groups.discourseservers }}"
