---
- name: Create volume for discourse data
  os_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    size: "{{ discourse.volume_size }}"
    wait: yes
    display_name: "{{ discourse.volume_name }}"

- name: create discourse security group
  os_security_group:
    name: discourse
    state: present
    cloud: "{{ auth.cloud }}"

- name: Open port 22
  os_security_group_rule:
    security_group: discourse
    state: present
    cloud: "{{ auth.cloud }}"
    port_range_min: 22
    port_range_max: 22
    protocol: tcp

- name: Open port 80
  os_security_group_rule:
    security_group: discourse
    state: present
    cloud: "{{ auth.cloud }}"
    port_range_min: 80
    port_range_max: 80
    protocol: tcp

- name: Open port 443
  os_security_group_rule:
    security_group: discourse
    state: present
    cloud: "{{ auth.cloud }}"
    port_range_min: 443
    port_range_max: 443
    protocol: tcp

- name: Create server auto_ip
  os_server:
    state: "present"
    cloud: "{{ auth.cloud }}"
    name: "{{ discourse.server_name }}"
    image: "{{ discourse.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ discourse.flavor }}"
    network: "{{ discourse.private_net }}"
    auto_ip: true
    security_groups: discourse
  register: discourse_temp1
  when: discourse.ips is not defined

- name: Create server with specified floating ips
  os_server:
    state: "present"
    cloud: "{{ auth.cloud }}"
    name: "{{ discourse.server_name }}"
    image: "{{ discourse.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ discourse.flavor }}"
    network: "{{ discourse.private_net }}"
    floating_ips: "{{ discourse.ips }}"
    security_groups: discourse
  register: discourse_temp2
  when: discourse.ips is defined

- name: register discourse1 var
  set_fact:
    discourse1: "{{ discourse_temp2 if discourse.ips is defined else discourse_temp1 }}"

- name: attach a volume for database to save data
  os_server_volume:
    state: present
    cloud: "{{ auth.cloud }}"
    server: "{{ discourse.server_name }}"
    volume: "{{ discourse.volume_name }}"
    device: "/dev/vdb"

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.public_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 != ""

- name: Add discourse server to discourse group
  add_host:
    name: "{{ discourse1.openstack.private_v4 }}"
    groups: discourseservers
  when: discourse1.openstack.public_v4 == ""

- name: wait for ssh
  wait_for:
    host: "{{ item }}"
    port: 22
    timeout: 60
    state: started
  with_items: "{{ groups.discourseservers }}"
